apiVersion: apps/v1
kind: Deployment
metadata:
  #the Deployment Name
  name: frontend
spec:
  #the Number of Pods
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Container Details
      containers:
      
      - name: frontend
        # Docker Image
        image: mohamedaminetaieb/client
        resources:
         #cpu and memory limit
          limits:
            memory: "10100Mi"
            cpu: "1000m"
        ports:
        #the port on which the app can be reached out inside the container
        - containerPort: 8000
