Master:
  ServicePort: 8080
  ServiceType: NodePort
  NodePort: 32123
  ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
  InstallPlugins:
  - kubernetes:1.7.1
  - workflow-aggregator:2.5
  - workflow-job:2.21
  - credentials-binding:1.16
  - git:3.9.1   
Agent:
  volumes:
    - type: HostPath
      hostPath: /var/run/docker.sock
      mountPath: /var/run/docker.sock

Persistence:
  Enabled: true
  StorageClass: jenkins-pv   
  Size: 50Gi

networkPolicy:
  Enabled: false
  apiVersion: extensions/v1beta1

rbac:
  create: true
  serviceAccount:
    name: default
  apiVersion: v1beta1