apiVersion: apps/v1
kind: Deployment
metadata:
  #the Deployment Name
  name: backend
spec:
  #the Number of Pods
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      # Container Details
      containers:

      - name: backend
        # Docker Image
        image: mohamedaminetaieb/server
        resources:
         #cpu and memory limit
          limits:
            memory: "10100Mi"
            cpu: "1000m"
        ports:
        #the port on which the app can be reached out inside the container
        - containerPort: 8000
