apiVersion: v1
kind: Service
metadata:
   #the Serivce Name- it should match with the lable name of the deployment
  name: backend
spec:
  #type of the service
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 32500
